[package]
name = "metrics"
version = "0.1.0"
authors = ["Didji <ngc_master@hotmail.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
